services:
  intelligence:
    build: ../intelligence # intelligence 폴더 빌드
    container_name: intelligence
    ports:
      - "5050:5050" # 외부에서도 직접 접근 가능 (선택)
    networks:
      - osint-net
    restart: unless-stopped

  osint-dashboard:
    build: .
    image: starmoby/osint-dashboard:latest
    container_name: osint-dashboard
    ports:
      - "8000:8000"
    volumes:
      - //192.168.45.80/etc_archive/OSINT_REPORT:/app/OSINT_REPORT
    environment:
      - INTELLIGENCE_URL=http://intelligence:5050 # 컨테이너 이름으로 자동 DNS 해석
    env_file:
      - .env
    depends_on:
      - intelligence # intelligence 먼저 시작
    networks:
      - osint-net
    restart: unless-stopped

networks:
  osint-net:
    driver: bridge
